version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: date-fns
    versions:
    - 2.18.0
    - 2.19.0
    - 2.20.1
    - 2.20.2
    - 2.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.2.0
  - dependency-name: redis
    versions:
    - 3.1.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.22.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: "@types/bcrypt"
    versions:
    - 3.0.1
  - dependency-name: googleapis
    versions:
    - 71.0.0
  - dependency-name: ioredis
    versions:
    - 4.26.0
  - dependency-name: node-cron
    versions:
    - 3.0.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.15
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.15
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
    - 7.13.15
  - dependency-name: yup
    versions:
    - 0.32.8
    - 0.32.9
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/nodemailer"
    versions:
    - 6.4.1
  - dependency-name: pug
    versions:
    - 3.0.2
  - dependency-name: "@types/jsonwebtoken"
    versions:
    - 8.5.1
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.4
  - dependency-name: slugify
    versions:
    - 1.5.0
  - dependency-name: nodemailer
    versions:
    - 6.5.0
  - dependency-name: swagger-jsdoc
    versions:
    - 6.0.8
    - 6.0.9
    - 6.1.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: bcrypt
    versions:
    - 5.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.15.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
  - dependency-name: "@babel/node"
    versions:
    - 7.12.13
    - 7.12.16
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
