version: '3.8'
services:
  app:
    build:
      context: .
    container_name: express_mongo_app
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - '7000:7000'
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      private_network:
        ipv4_address: 172.16.234.10
  db:
    image: mongo:latest
    container_name: express_mongo_db
    volumes:
      - './storage/mongo-volume:/data/db:rw'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    restart: always
    ports:
      - '27018:27017'
    networks:
      private_network:
        ipv4_address: 172.16.234.11
  redis:
    image: 'redis:alpine'
    container_name: express_mongo_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./storage/redis-data:/var/lib/redis
    restart: always
    networks:
      private_network:
        ipv4_address: 172.16.234.12
networks:
  private_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.234.0/24
